### PR TITLE
Update Common.scss

### PR DESCRIPTION
**Pull request by vaibhav-synapsesai**

### CODE REVIEW

**Comment by karelkral** [comment]
What is the purpose of changing the width to 101%? Some explanation is needed.

**Comment by vaibhav-synapsesai** [comment]
Sorry i only change for my practice .i am the devOps guy .i create a CI CD
pipeline so i checked that CI CD work properly or not.

**Comment by karelkral** [comment]
Then you should cancel this public PR.

**Comment by vaibhav-synapsesai** [comment]
Ok i will

**Pull request closed without merging**
