### PR TITLE
Fixed styling of components by using a newer version of style-loader

### PR DESCRIPTION
**Pull request by marcveens**
Upgraded version of style-loader since styling wasn't working for me, same issue as #109. Used `asset/inline` feature of webpack 5, `base64-inline-loader` is now unnecessary.

### CODE REVIEW

**Comment by romeguarin** [comment]
This should come into the master branch, any idea how to approve this PR and have it completed?

**Comment by mehmetyuksel41** [comment]
This needs to be merged. Current status is highly misleading.

**Comment by marcveens** [comment]
@scottdallamura are you able to merge this PR?

**Review by mahomedalid — APPROVED** [review]

**Comment by bworline** [comment]
These changes were included in #153.  The PR can be closed.

**Pull request closed without merging**
